# ~/.config/tmux/tmux.conf
set -g default-terminal "xterm-256color"
set-option -sa terminal-features ',xterm-256color:RGB'
set-option -g default-terminal "tmux-256color"
set-option -ga terminal-features ",xterm-256color:usstyle"
# Set prefix to Ctrl-a
# set -g prefix M-a
set -g prefix M-b
# unbind C-b
# bind M-a send-prefix
bind M-b send-prefix

# Reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Config reloaded"

bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt
set -g detach-on-destroy off  # don't exit from tmux when closing a session

# Enable mouse support
set -g mouse on

# Start window numbering at 1
set -g base-index 1

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @plugin 'omerxx/tmux-sessionx'

# set -g @sessionx-bind 'o'
# set -g @sessionx-fzf-builtin-tmux 'on'
# set -g @sessionx-zoxide-mode 'false'
# set -g @sessionx-window-mode 'false'
# set -g @sessionx-tree-mode 'on'
# set -g @sessionx-custom-paths-subdirectories 'false'
bind-key "o" run-shell "sesh connect \"$(
  sesh list -H --icons | fzf-tmux -p 80%,70% \
    --no-sort --ansi --border-label ' sesh ' --prompt '⚡  ' \
    --header '  ^a all ^t tmux ^g configs ^x zoxide ^d tmux kill ^f find' \
    --bind 'tab:down,btab:up' \
    --bind 'ctrl-a:change-prompt(⚡  )+reload(sesh list --icons)' \
    --bind 'ctrl-t:change-prompt(🪟  )+reload(sesh list -t --icons)' \
    --bind 'ctrl-g:change-prompt(⚙️  )+reload(sesh list -c --icons)' \
    --bind 'ctrl-x:change-prompt(📁  )+reload(sesh list -z --icons)' \
    --bind 'ctrl-f:change-prompt(🔎  )+reload(fd -H -d 2 -t d -E .Trash . ~)' \
    --bind 'ctrl-d:execute(tmux kill-session -t {2..})+change-prompt(⚡  )+reload(sesh list --icons)' \
    --preview-window 'right:55%' \
    --preview 'sesh preview {}'
)\""


set-option -g status-position bottom 
set -g status-right "󰥔 %H:%M"
# 211 198 170
# d3c6aa
# 
#    󰈸
# status=$(#[bg=#d3c6aa,fg=#35a77C]#{?client_prefix,"a"," "})
prefixStatus=$(#[bg=#D3C6AA,fg=#2d353b,bold] #{?client_prefix,󰈸,})
set -g status-left "#[bg=#D3C6AA,fg=#2d353b,bold] #{?client_prefix,󰈸,}  #[fg=#D3C6AA,bg=#4B565C,none]#[fg=#DFDDC1,bg=#4B565C]  #S #[bg=#2d353b,fg=#4B565C]"
# set -g status-left "#[bg=#d3c6aa,fg=#35a77C,bold]#{?client_prefix,"󰈸",""}#[fg=#DFDDC10,bg=#4B565C] #S #[bg=#2d353b,fg=#4B565C]"
# Using solid blocks

set-option -g status-left-length 40
set-option -g status-style bg=#2d353b,fg=white
set-window-option -g window-status-format '#[bg=#2d353b,fg=#35a77C,bold]  #I #W '
# set-window-option -g window-status-format '#[bg=#5d353b,fg=#35a77C,bold]#I #W'
set-window-option -g window-status-current-format '#[fg=#2d353b,bg=#35a77C,bold] #I  #W '
# Using powerline-style separators
# set-window-option -g window-status-format '#[fg=colour244,bg=colour234]#[fg=colour240] #I #[fg=colour244]❯#[fg=colour240] #W #[fg=colour234,bg=colour234]'
# set-window-option -g window-status-current-format '#[fg=colour234,bg=colour31]#[fg=colour117,bg=colour31] #I #[fg=colour231]❯ #W #[fg=colour31,bg=colour234]'


bind -N "last-session (via sesh) " l run-shell "sesh last"

run '~/.config/tmux/plugins/tpm/tpm'

